package CleanCode.DesignPattern.FactoryMethodPattern.ConcreteCreator;

import FactoryMethodPattern.ConcreteProduct.Truck;
import FactoryMethodPattern.Interface.Transport;

public class RoadLogistics extends Logistics{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    @Override
    public Transport createTransport(){
        return new Truck();
    }
}
