package CleanCode.DesignPattern.FactoryMethodPattern.ConcreteCreator;

import CleanCode.DesignPattern.FactoryMethodPattern.Creator.Logistics;
import CleanCode.DesignPattern.FactoryMethodPattern.Interface.Transport;
import CleanCode.DesignPattern.FactoryMethodPattern.ConcreteProduct.Truck;

public class RoadLogistics extends Logistics{                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    @Override
    public Transport createTransport(){
        return new Truck();
    }
}
